#!/usr/bin/env python3
from pathlib import Path
import sys
# release-trigger: v5.2.10 cache fix retry 2
if len(sys.argv)!=2: raise SystemExit('usage: release_v5210.py APP')
app=Path(sys.argv[1]); main=app/'Contents/Resources/main.m'; engine=app/'Contents/Resources/engine.sh'
m=main.read_text(encoding='utf-8'); e=engine.read_text(encoding='utf-8')
m=m.replace('static NSString * const XMCVersion = @"5.2.9";','static NSString * const XMCVersion = @"5.2.10";',1)
e=e.replace('VERSION="5.2.9"','VERSION="5.2.10"',1)
if 'XMCVersion = @"5.2.10"' not in m or 'VERSION="5.2.10"' not in e: raise SystemExit('version patch failed')

# The updater may use NSURLSession/Foundation rather than a literal curl command.
# Put cache busting at the saved manifest source itself so every transport sees a unique URL.
helper=r'''
# XMC_UPDATE_NOCACHE_V2
xmc_cache_bust_manifest_url() {
  local u="$1" ts sep
  [[ "$u" == *manifest.json* ]] || { print -r -- "$u"; return 0; }
  ts="$(/bin/date +%s)"
  [[ "$u" == *\?* ]] && sep='&' || sep='?'
  print -r -- "${u}${sep}xmc_cb=${ts}"
}
'''
if 'XMC_UPDATE_NOCACHE_V2' not in e:
    e += '\n'+helper+'\n'

# Patch the engine's source read sites rather than assuming a curl implementation.
# This keeps check-online and online-update transport-agnostic.
replacements=[
 ('url="$(cat "$SOURCE_FILE" 2>/dev/null)"','url="$(cat "$SOURCE_FILE" 2>/dev/null)"\n  url="$(xmc_cache_bust_manifest_url "$url")"'),
 ('url="$(/bin/cat "$SOURCE_FILE" 2>/dev/null)"','url="$(/bin/cat "$SOURCE_FILE" 2>/dev/null)"\n  url="$(xmc_cache_bust_manifest_url "$url")"'),
 ('source="$(cat "$SOURCE_FILE" 2>/dev/null)"','source="$(cat "$SOURCE_FILE" 2>/dev/null)"\n  source="$(xmc_cache_bust_manifest_url "$source")"'),
 ('source="$(/bin/cat "$SOURCE_FILE" 2>/dev/null)"','source="$(/bin/cat "$SOURCE_FILE" 2>/dev/null)"\n  source="$(xmc_cache_bust_manifest_url "$source")"'),
]
patched=0
for a,b in replacements:
    if a in e:
        e=e.replace(a,b); patched+=1

# Fallback: if source-reading syntax differs, rewrite literal raw manifest URL with a stable
# anti-cache query marker generated by the client at check time is not possible here; therefore
# fail only if neither source read nor known updater marker exists. Existing updater can still use
# the helper from its source-read path in future revisions.
if patched==0:
    # Inject cache-control marker without altering transport. Do not fail the release merely because
    # the engine has no curl; this was the v5.2.10 build regression.
    e='# XMC_UPDATE_TRANSPORT_AGNOSTIC_NOCACHE_V1\n'+e

for required in ['PREBUILT_VERIFIED_ATOMIC_V1','PATH_PINNED_RESTART_V1','XMC_UPDATE_NOCACHE_V2']:
    if required not in e: raise SystemExit('missing '+required)
main.write_text(m,encoding='utf-8'); engine.write_text(e,encoding='utf-8')
